// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAAYm4lH-8s52y5_9am9zFAsNn9xh99uE',
    appId: '1:335507088127:web:4aec8095e5d588abf0a2ca',
    messagingSenderId: '335507088127',
    projectId: 'mediscan-3d1a3',
    authDomain: 'mediscan-3d1a3.firebaseapp.com',
    storageBucket: 'mediscan-3d1a3.firebasestorage.app',
    measurementId: 'G-8GZG1YWELG',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOln_N5Pt59jbyKSDoGz9m5Xd2PXwZdAw',
    appId: '1:335507088127:ios:d238be54458c2751f0a2ca',
    messagingSenderId: '335507088127',
    projectId: 'mediscan-3d1a3',
    storageBucket: 'mediscan-3d1a3.firebasestorage.app',
    iosBundleId: 'com.example.mediscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOln_N5Pt59jbyKSDoGz9m5Xd2PXwZdAw',
    appId: '1:335507088127:ios:d238be54458c2751f0a2ca',
    messagingSenderId: '335507088127',
    projectId: 'mediscan-3d1a3',
    storageBucket: 'mediscan-3d1a3.firebasestorage.app',
    iosBundleId: 'com.example.mediscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAAYm4lH-8s52y5_9am9zFAsNn9xh99uE',
    appId: '1:335507088127:web:f70ccba779711b12f0a2ca',
    messagingSenderId: '335507088127',
    projectId: 'mediscan-3d1a3',
    authDomain: 'mediscan-3d1a3.firebaseapp.com',
    storageBucket: 'mediscan-3d1a3.firebasestorage.app',
    measurementId: 'G-M2264KX8KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9jfzqTyOt7ufhDKpdPpVs1XeP_x4N3IU',
    appId: '1:335507088127:android:3998728386b40aaff0a2ca',
    messagingSenderId: '335507088127',
    projectId: 'mediscan-3d1a3',
    storageBucket: 'mediscan-3d1a3.firebasestorage.app',
  );

}